name: "Commit: Lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HUSKY_SKIP: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
