name: Release (manually)

on:
  workflow_dispatch:

env:
  HUSKY_SKIP: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          npm run release:publish-manual
        env:
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
